# Site settings
title: Jacob Young - Software Engineer
email: jacob@jacobyoung.me
description: > # this means to ignore newlines until "baseurl:"
  iOS Programmer, Web Developer, and Coffee Purist. Loves making awesome software and eSports. Hates indecisiveness.
about: > # this means to ignore newlines until "baseurl:"
  I'm a student at [Diablo Valley College](http://dvc.edu) working on 
  transfering to UC Berkeley's undergraduate Computer Science program.

  Most of my time is spent writing and learning Objective-C and iOS. I'm 
  passionate about writing, programming, and properly roasted coffee... 
  because you know, no one wants to drink motor oil.

  I love attending hackathons. I've hacked at [CalHacks](http://calhacks.io), [HackJam](https://www.facebook.com/events/1569464466625216/), [
  TreeHacks](http://treehacks.com), and recently [LAHacks](http://lahacks.
  com). 

  I' m currently looking for jobs or internships for summer 2015 and 
  beyond. If you're interested in filling an entry level position, feel 
  free to [reach out](mailto:{{ site.email }}).
baseurl: "/" # the subpath of your site, e.g. /blog/
permalink: /blog/:title
url: "https://jacobyoung.me" # the base hostname & protocol for your site
favicon: assets/images/inverted-apple-touch-icon-152x152.png
timezone: America/Los_Angeles
twitter_username: JakeRYoung
github_username: JacobRYoung
linkedin_username: jacobryoung
reddit_username: JewCFroot
keybase_username: JacobYoung
keywords: 
    - Jacob Yong
    - JacobYoung
    - JacobRYoung
    - JakeRYoung
    - JewCFroot
    - student
    - developer
    - intern
    - software engineer
    - web applications
    - iOS
collections:
    - projects

# Build settings
markdown: redcarpet
