# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# Use of '/:title' permalinks allows for 'base.io/title' urls
permalink:           /posts/:title
relative_permalinks: true

# Setup
title:               Jacob Young
short_title:         JRY
url:                 http://jry.io
baseurl:             ""
images_path:           "/assets/images/"

# Defaults
#
# Gives all "posts" the variable is_post = true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
me:
  name:              Jacob Young
  email:             jacob@jry.io
  twitter:
    username:        jryio
    url:             https://twitter.com/jryio
  github:
    username:        thebearjew
    url:             https://github.com/thebearjew
  linedin:
    username:        jacobryoung
    url:             https://linkedin.com/in/jacobryoung
  pgp:
    keybase:         https://keybase.io/jacobyoung

