# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# Use of '/:title' permalinks allows for 'base.io/title' urls
permalink:           posts/:title

# Setup
title:               Jacob Young
short_title:         JRY
url:                 http://jry.io
baseurl:             "/"
images_path:         "/assets/images/"
excerpt_separator:   "\n\n"

# Defaults
#
# Gives all "posts" the variable is_post = true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true

# About/contact
#
# Some commonly used personal information and links
name:              Jacob Young
email:             jacob@jry.io
twitter:
  username:        jryio
  url:             https://twitter.com/jryio
github:
  username:        thebearjew
  url:             https://github.com/thebearjew
linkedin:
  username:        jacobryoung
  url:             https://linkedin.com/in/jacobryoung

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Markdown
#
# Configuring and using Markdown Processors
markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["fenced_code_blocks", "highlight", "footnotes", "superscript", "underline", "strikethrough", "tables"]

# Gems
#
# Using jemoji gem with github-pages gem to use emoji by default on this site!
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-gist
  - jekyll-sitemap
  