# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# Use of '/:title' permalinks allows for 'base.io/title' urls
permalink:           /posts/:title
relative_permalinks: true

# Setup
title:               Jacob Young
url:                 http://jry.io
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
me:
  name:              Jacob Young
  email:             jacob@jry.io
  twitter:
    username:        jryio
    url:             https://twitter.com/jryio
  github:
    username:        thebearjew
    url:             https://github.com/thebearjew
  pgp:
    keybase:         https://keybase.io/jacobyoung

