# Site settings
title: Jacob Young-Software Engineer
email: jacob@jacobyoung.me
description: > # this means to ignore newlines until "baseurl:"
  I'm a full time student working on transfering to UC Berkeley. I'm also an iOS/front end developer working on several personal projets while exploring new programming paradigms. I write about tech, hacakthons, and developing; you might find something interesting, have a read.
baseurl: "/" # the subpath of your site, e.g. /blog/
permalink: /posts/:title
url: "https://jacobyoung.me" # the base hostname & protocol for your site
favicon: /assets/images/inverted-apple-touch-icon-152x152.png
timezone: America/Los_Angeles
twitter_username: JakeRYoung
github_username: JacobRYoung
linkedin_username: jacobryoung
reddit_username: JewCFroot
keybase_username: JacobYoung
keywords: 
    - Jacob Yong
    - JacobYoung
    - JacobRYoung
    - JakeRYoung
    - JewCFroot
    - student
    - developer
    - intern
    - software engineer
    - web applications
    - iOS
collections:
    - projects

# Build settings
markdown: redcarpet
